# Generated by Django 5.2 on 2026-06-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Студент'), ('ASSISTANT', 'Ассистент'), ('TRAINER', 'Тренер')], max_length=15, verbose_name='Роль')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.position', verbose_name='Должность')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания')),
                ('company_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='people.companyperson', verbose_name='Человек в компании')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='catalog.coursesession', verbose_name='Запуск курса')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'ordering': ['-session__start_date', 'role'],
                'unique_together': {('company_person', 'session', 'role')},
            },
        ),
    ]
