# Generated by Django 5.2 on 2026-06-01 09:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_callers', models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные прозвонщики')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Встреча / прозвон',
                'verbose_name_plural': 'Встречи / прозвоны',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCallRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_CALLED', 'Не звонили'), ('WILL_COME', 'Придёт'), ('WONT_COME', 'Не придёт'), ('MAYBE', 'Возможно придёт'), ('NO_ANSWER', 'Не берёт трубку')], default='NOT_CALLED', max_length=15, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время захвата')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('called_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Позвонил')),
                ('claimed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Взял в работу')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.company', verbose_name='Компания')),
                ('company_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.companyperson', verbose_name='Человек в компании')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='calling.event', verbose_name='Встреча')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Отметка прозвона',
                'verbose_name_plural': 'historical Отметки прозвона',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_CALLED', 'Не звонили'), ('WILL_COME', 'Придёт'), ('WONT_COME', 'Не придёт'), ('MAYBE', 'Возможно придёт'), ('NO_ANSWER', 'Не берёт трубку')], default='NOT_CALLED', max_length=15, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время захвата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_records', to=settings.AUTH_USER_MODEL, verbose_name='Позвонил')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_records', to=settings.AUTH_USER_MODEL, verbose_name='Взял в работу')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания')),
                ('company_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='people.companyperson', verbose_name='Человек в компании')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='calling.event', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Отметка прозвона',
                'verbose_name_plural': 'Отметки прозвона',
                'unique_together': {('event', 'company_person')},
            },
        ),
    ]
