# Generated by Django 5.2 on 2026-06-01

from django.db import migrations, models


def copy_user_callers_to_people(apps, schema_editor):
    Event = apps.get_model("calling", "Event")
    CompanyPerson = apps.get_model("people", "CompanyPerson")

    for event in Event.objects.all():
        for user in event.assigned_callers.all():
            person_id = getattr(user, "person_id", None)
            if not person_id:
                continue
            company_person = CompanyPerson.objects.filter(
                company_id=event.company_id,
                person_id=person_id,
            ).first()
            if company_person:
                event.assigned_people.add(company_person)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_person"),
        ("calling", "0001_initial"),
        ("people", "0002_alter_companyperson_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="assigned_people",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="people.companyperson",
                verbose_name="Назначенные прозвонщики",
            ),
        ),
        migrations.RunPython(copy_user_callers_to_people, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="event",
            name="assigned_callers",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="assigned_people",
            new_name="assigned_callers",
        ),
        migrations.AlterField(
            model_name="event",
            name="assigned_callers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_call_events",
                to="people.companyperson",
                verbose_name="Назначенные прозвонщики",
            ),
        ),
    ]
