# Generated by Django 5.2 on 2026-06-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_person'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyperson',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companyperson',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddConstraint(
            model_name='companyperson',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'person'), name='uniq_company_person_when_company_set'),
        ),
    ]
